"""Updated Passwords last_login to last_edited

Revision ID: c6c5a2065beb
Revises: c32ef7995544
Create Date: 2025-07-01 20:19:08.596754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c5a2065beb'
down_revision = 'c32ef7995544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edited', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_passwords_last_login'))
        batch_op.create_index(batch_op.f('ix_passwords_last_edited'), ['last_edited'], unique=False)
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_passwords_last_edited'))
        batch_op.create_index(batch_op.f('ix_passwords_last_login'), ['last_login'], unique=False)
        batch_op.drop_column('last_edited')

    # ### end Alembic commands ###
